<?php

namespace ContainerXuC6D1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VLD2CKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VLD2CK_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VLD2CK_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'booksRepository' => ['privates', 'App\\Repository\\BooksRepository', 'getBooksRepositoryService', true],
        ], [
            'booksRepository' => 'App\\Repository\\BooksRepository',
        ]);
    }
}
