<?php

namespace ContainerXuC6D1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDealerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DealerController' shared autowired service.
     *
     * @return \App\Controller\DealerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DealerController.php';

        $container->services['App\\Controller\\DealerController'] = $instance = new \App\Controller\DealerController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\DealerController', $container));

        return $instance;
    }
}
