<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuC6D1x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuC6D1x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuC6D1x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuC6D1x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuC6D1x\App_KernelDevDebugContainer([
    'container.build_hash' => 'XuC6D1x',
    'container.build_id' => '321ed2b3',
    'container.build_time' => 1685111034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuC6D1x');
