<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9hetoi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9hetoi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX9hetoi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX9hetoi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX9hetoi\App_KernelDevDebugContainer([
    'container.build_hash' => 'X9hetoi',
    'container.build_id' => 'b24f8e3c',
    'container.build_time' => 1681676493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9hetoi');
