<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'game' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::game'], [], [['text', '/game']], [], [], []],
    'init' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::init'], [], [['text', '/game/init']], [], [], []],
    'make-bet' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::makeBet'], [], [['text', '/game/make-bet']], [], [], []],
    'bet' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::bet'], [], [['text', '/game/bet']], [], [], []],
    'game21' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::game21'], [], [['text', '/game/game21']], [], [], []],
    'hit' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::hit'], [], [['text', '/game/hit']], [], [], []],
    'cpuHit' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::cpuHit'], [], [['text', '/game/cpuHit']], [], [], []],
    'doc' => [[], ['_controller' => 'App\\Controller\\MeControllerGame::doc'], [], [['text', '/game/doc']], [], [], []],
    'game_api' => [[], ['_controller' => 'App\\Controller\\MeControllerGameJson::gameApi'], [], [['text', '/api/game']], [], [], []],
    'quote' => [[], ['_controller' => 'App\\Controller\\MeControllerJson::quote'], [], [['text', '/api/quote']], [], [], []],
    'deck_api' => [[], ['_controller' => 'App\\Controller\\MeControllerJson::deck'], [], [['text', '/api/deck']], [], [], []],
    'shuffle_api' => [[], ['_controller' => 'App\\Controller\\MeControllerJson::shuffleCard'], [], [['text', '/api/deck/shuffle']], [], [], []],
    'single_api' => [[], ['_controller' => 'App\\Controller\\MeControllerJson::drawCard'], [], [['text', '/api/deck/draw']], [], [], []],
    'many_api' => [[], ['_controller' => 'App\\Controller\\MeControllerJson::drawMany'], [], [['text', '/api/deck/draw/']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::home'], [], [['text', '/']], [], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::about'], [], [['text', '/about']], [], [], []],
    'lucky' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::number'], [], [['text', '/lucky']], [], [], []],
    'report' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::report'], [], [['text', '/report']], [], [], []],
    'api' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::api'], [], [['text', '/api']], [], [], []],
    'card' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::card'], [], [['text', '/card']], [], [], []],
    'deck' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::deck'], [], [['text', '/card/deck']], [], [], []],
    'shuffle' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::shuffleCard'], [], [['text', '/card/deck/shuffle']], [], [], []],
    'draw' => [[], ['_controller' => 'App\\Controller\\MeControllerTwig::drawCard'], [], [['text', '/card/deck/draw']], [], [], []],
    'draw_many' => [['num'], ['_controller' => 'App\\Controller\\MeControllerTwig::drawMany'], ['num' => '\\d+'], [['variable', '/', '\\d+', 'num', true], ['text', '/card/deck/draw']], [], [], []],
];
